"""update user model, add tables, add meetings model

Revision ID: 94b67fc59517
Revises: d1f54af08e89
Create Date: 2020-10-06 00:03:01.492851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b67fc59517'
down_revision = 'd1f54af08e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=1000), nullable=False),
    sa.Column('virtual', sa.Boolean(), nullable=True),
    sa.Column('zoom_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor_table',
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('sponsee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sponsor_id', 'sponsee_id')
    )
    op.create_table('user_meeting',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'meeting_id')
    )
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('sponsee', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sponsor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'zipcode')
    op.drop_column('users', 'sponsor')
    op.drop_column('users', 'sponsee')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'bio')
    op.drop_table('user_meeting')
    op.drop_table('sponsor_table')
    op.drop_table('meetings')
    # ### end Alembic commands ###
